version: "3.8"

services:
  user:
    build: ./user-service
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
    networks:
      - ecommerce

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - ecommerce

  order:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./order-service/.env
    networks:
      - ecommerce

  product:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./product-service/.env
    networks:
      - ecommerce

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - ecommerce

networks:
  ecommerce:
