version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/seuBancoDeDados
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
